syntax = "proto3";

package channels;

import "google/protobuf/timestamp.proto";

service ChannelService {
	rpc CreateChannel (CreateChannelRequest) returns (CreateChannelResponse);
	rpc DeleteChannel (DeleteChannelRequest) returns (DeleteChannelResponse);
	rpc GetChannel (GetChannelRequest) returns (GetChannelResponse);
	rpc ValidateAuthenticationDetails (ChannelAuthenticationDetailsRequest) returns (ChannelAuthenticationDetailsResponse);
}

message CreateChannelRequest {
	string user_id = 1;
	string name = 2;
}

message CreateChannelResponse {
	Channel channel = 1;
}

message DeleteChannelRequest {
	string channel_id = 1;
}

message DeleteChannelResponse {
	bool deleted = 1;
}

message GetChannelRequest {
	string channel_id = 1;
}

message GetChannelResponse {
	Channel channel = 1;
}

message ChannelAuthenticationDetailsRequest {
	string user_id = 1;
	string channel_id = 2;
}

message ChannelAuthenticationDetailsResponse {
	bool valid = 1;
	optional string channel_id = 2;
}

message Channel {
	string id = 1;
	string user_id = 2;
	string name = 3;
	optional string description = 4;
	string subscriber_count = 5;
	google.protobuf.Timestamp created_date = 6;
	google.protobuf.Timestamp updated_date = 7;
}