syntax = "proto3";

package users;

import "google/protobuf/timestamp.proto";

service UserService {
	rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
	rpc UserExists (UserExistsRequest) returns (UserExistsResponse);
}

message CreateUserRequest {
	string email = 1;
	google.protobuf.Timestamp date_of_birth = 2;
	string password = 3;
}

message CreateUserResponse {
	User user = 1;
}

message UserExistsRequest {
	oneof user_id_or_email {
		string user_id = 1;
		string email = 2;
	}
}

message UserExistsResponse {
	bool exists = 1;
}

message User {
	string id = 1;
	string email = 2;
	google.protobuf.Timestamp date_of_birth = 3;
	google.protobuf.Timestamp created_date = 4;
	google.protobuf.Timestamp updated_date = 5;
}