syntax = "proto3";

package users;

import "google/protobuf/timestamp.proto";

service UserService {
	rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
	rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
	rpc UserExists (UserExistsRequest) returns (UserExistsResponse);
	rpc ValidateAuthenticationDetails (UserAuthenticationDetailsRequest) returns (UserAuthenticationDetailsResponse);
	rpc CanAccessNsfw (CanAccessNsfwRequest) returns (CanAccessNsfwResponse);
}

message CreateUserRequest {
	string email = 1;
	google.protobuf.Timestamp date_of_birth = 2;
	string password_hash = 3;
}

message CreateUserResponse {
	User user = 1;
}

message DeleteUserRequest {
	string user_id = 1;
}

message DeleteUserResponse {
	bool deleted = 1;
}

message UserExistsRequest {
	oneof user_id_or_email {
		string user_id = 1;
		string email = 2;
	}
}

message UserExistsResponse {
	bool exists = 1;
}

message UserAuthenticationDetailsRequest {
	string email = 1;
	string password = 2;
}

message UserAuthenticationDetailsResponse {
	bool valid = 1;
	optional string user_id = 2;
}

message CanAccessNsfwRequest {
	string user_id = 1;
}

message CanAccessNsfwResponse {
	bool can_access_nsfw = 1;
}

message User {
	string id = 1;
	string email = 2;
	google.protobuf.Timestamp date_of_birth = 3;
	google.protobuf.Timestamp created_date = 4;
	google.protobuf.Timestamp updated_date = 5;
}