syntax = "proto3";

package videos;

import "google/protobuf/timestamp.proto";

service VideoService {
	rpc CreateVideo (CreateVideoRequest) returns (CreateVideoResponse);
	rpc GetVideo (GetVideoRequest) returns (GetVideoResponse);
}

message CreateVideoRequest {
	string title = 1;
	string channel_id = 2;
}

message CreateVideoResponse {
	Video video = 1;
}


message GetVideoRequest {
	string video_id = 1;
	string user_id = 2;
	string channel_id = 3;
}

message GetVideoResponse {
	Video video = 1;
}

message Video {
	string id = 1;
	string channel_id = 2;
	string channel_name = 3;
	string title = 4;
	optional string description = 5;
	repeated string tags = 6;
	bool allow_comments = 7;
	bool allow_rates = 8;
	string selected_thumbnail = 9;
	string visibility = 10;
	bool is_published = 11;
	bool is_nsfw = 12;
	string view_count = 13;
	string likes = 14;
	string dislikes = 15;
	google.protobuf.Timestamp created_date = 16;
	google.protobuf.Timestamp updated_date = 17;
}