/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum VideoSelectedThumbnail {
  Custom = "custom",
  First = "first",
  Second = "second",
  Third = "third",
}

export enum VideoVisibility {
  AccessibleByLink = "accessible_by_link",
  Private = "private",
  Public = "public",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Video {
  allowComments: Generated<boolean>;
  allowRates: Generated<boolean>;
  channelId: string;
  channelName: string;
  createdDate: Generated<Timestamp>;
  description: Generated<string | null>;
  dislikes: Generated<Int8>;
  id: Generated<string>;
  isNsfw: Generated<boolean>;
  isPublished: Generated<boolean>;
  likes: Generated<Int8>;
  selectedThumbnail: Generated<VideoSelectedThumbnail>;
  tags: Generated<string[]>;
  title: string;
  updatedDate: Generated<Timestamp>;
  viewCount: Generated<Int8>;
  visibility: Generated<VideoVisibility>;
}

export interface DB {
  videos: Video;
}
