/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Subscription {
  createdDate: Generated<Timestamp>;
  id: Generated<string>;
  subscribedChannelId: string;
  subscribedChannelName: string;
  subscriberChannelId: string;
  updatedDate: Generated<Timestamp>;
}

export interface DB {
  subscriptions: Subscription;
}
