/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum VideoUploadStatus {
  Processing = "processing",
  ProcessingCompleted = "processing_completed",
  ProcessingFailed = "processing_failed",
  Uploading = "uploading",
  UploadingCompleted = "uploading_completed",
  UploadingFailed = "uploading_failed",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface VideoUpload {
  channelId: string;
  createdDate: Generated<Timestamp>;
  id: Generated<string>;
  originalFilename: string;
  originalMimetype: string;
  originalSize: Int8;
  status: Generated<VideoUploadStatus>;
  updatedDate: Generated<Timestamp>;
  videoId: string;
}

export interface DB {
  videoUploads: VideoUpload;
}
