/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum CommentRateType {
  Dislike = "dislike",
  Like = "like",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CommentRate {
  channelId: string;
  commentId: string;
  createdDate: Generated<Timestamp>;
  id: Generated<string>;
  type: CommentRateType;
  updatedDate: Generated<Timestamp>;
}

export interface DB {
  commentRates: CommentRate;
}
