server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # Restrict to only GET/HEAD

    if ($request_method !~ ^(GET|HEAD)$) {
        return 405;
    }

    # CORS
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, HEAD' always;
    add_header 'Access-Control-Allow-Headers' 'Range, Accept, Origin, Content-Type' always;
    add_header 'Access-Control-Expose-Headers' 'Content-Length, Content-Range' always;

    # Enable gzip for text-based HLS playlists
    gzip on;
    gzip_types application/vnd.apple.mpegurl;
    gzip_min_length 512;

    # HLS segments + playlists
    location ~ ^/videos/[^/]+/hls/ {
        autoindex off;

        add_header Accept-Ranges bytes always;
        types {
            application/vnd.apple.mpegurl m3u8;
            video/MP2T ts;
        }

        # Cache rules:
        location ~ \.m3u8$ {
            add_header Cache-Control "public, max-age=5, must-revalidate" always;
        }

        location ~ \.ts$ {
            add_header Cache-Control "public, max-age=31536000, immutable" always;
        }

        try_files $uri =404;
    }

    # Current thumbnail
    location ~ ^/videos/[^/]+/thumbnails/current\.jpg$ {
        autoindex off;
        add_header Accept-Ranges bytes always;
        types {
            image/jpeg jpg;
        }

        add_header Cache-Control "public, max-age=3600, must-revalidate" always;

        try_files $uri =404;
    }

    # Block everything else
    location / {
        return 403;
    }
}
