/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Channel {
	createdDate: Generated<Timestamp>;
	description: Generated<string | null>;
	id: Generated<string>;
	name: string;
	subscriberCount: Generated<Int8>;
	updatedDate: Generated<Timestamp>;
	userId: string;
}

export interface DB {
	channels: Channel;
}
