/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Comment {
  channelId: string;
  channelName: string;
  content: string;
  createdDate: Generated<Timestamp>;
  dislikes: Generated<Int8>;
  id: Generated<string>;
  likes: Generated<Int8>;
  parentId: string | null;
  replyCount: Generated<Int8>;
  updatedDate: Generated<Timestamp>;
  videoId: string;
}

export interface DB {
  comments: Comment;
}
